'use strict';
const $=id=>document.getElementById(id);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=structuredClone(window.MOCK_ITEMS), results=[], selected=null, filter='ALL', fileName='', busy=false, editing=null, returnFocus=null;
const labels={CONFIGURED:'☑ 已配置',MISSING:'✕ 未配置',STRUCK_OUT:'已划线 / 删除线'};
const classes={CONFIGURED:'configured',MISSING:'missing',STRUCK_OUT:'struck'};
function notice(message=''){ $('notice').textContent=message; }
function badge(result){return `<span class="status ${classes[result.status]}">${labels[result.status]}</span>`;}
function setTab(manage){$('workspace').hidden=manage;$('management').hidden=!manage;$('workspaceTab').classList.toggle('active',!manage);$('manageTab').classList.toggle('active',manage);if(manage)renderManagement();}
function loadFile(name){if(busy)return;fileName=name;results=[];selected=null;$('filename').textContent=name;$('docstate').textContent='已选择 · 尚未核查';$('dropzone').hidden=true;$('ready').hidden=false;$('results').hidden=true;$('run').disabled=false;notice('已选择文件名。原型不读取内容，将使用固定的示例证据。');}
function acceptFiles(files){if(files.length!==1){notice('请一次选择一个 .docx 文件。');return;}if(!/\.docx$/i.test(files[0].name)){notice('不支持此文件类型。请选择 .docx 文件（不支持 .doc / PDF）。');return;}loadFile(files[0].name);}
$('choose').onclick=()=>$('file').click();$('file').onchange=e=>{if(e.target.files.length)acceptFiles(e.target.files);e.target.value='';};
$('dropzone').onclick=e=>{if(!e.target.closest('#sample'))$('file').click();};$('dropzone').onkeydown=e=>{if(e.target===$('dropzone')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();$('file').click();}};
$('sample').onclick=e=>{e.stopPropagation();loadFile('示例订单_GAG_设计开发要求.docx');};
window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>e.preventDefault());
$('workspace').ondragover=e=>{e.preventDefault();$('dropzone').classList.add('drag');};$('workspace').ondragleave=()=>$('dropzone').classList.remove('drag');$('workspace').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('drag');if(!busy)acceptFiles(e.dataTransfer.files);};
$('run').onclick=()=>{if(!fileName||busy)return;busy=true;$('run').disabled=true;$('choose').disabled=true;$('manageTab').disabled=true;$('docstate').textContent='正在生成模拟结果…';$('run').textContent='模拟核查中…';notice();setTimeout(()=>{results=items.filter(i=>i.enabled).map(i=>({item:i,...(i.fixture||{status:'MISSING',type:null,actual:null,changed:false,noFixture:true})}));selected=null;filter='ALL';$('search').value='';busy=false;$('run').disabled=false;$('choose').disabled=false;$('manageTab').disabled=false;$('run').textContent='重新模拟核查';$('docstate').textContent='模拟核查完成';$('ready').hidden=true;$('results').hidden=false;notice('模拟结果：来自示例数据，并非所选 DOCX 的检测结论。');renderResults();},450);};
function visibleResults(){const q=$('search').value.trim().toLowerCase();return results.filter(r=>(filter==='ALL'||filter===r.status||(filter==='EXCEPTIONS'&&(r.status!=='CONFIGURED'||r.changed)))&&[r.item.code,r.item.name,r.item.category,r.item.expectedDescription].join(' ').toLowerCase().includes(q)).sort((a,b)=>rank(a)-rank(b));}
function rank(r){return r.status==='MISSING'?0:r.status==='STRUCK_OUT'?1:r.changed?2:3;}
function renderResults(){const count=s=>results.filter(r=>r.status===s).length;$('summary').innerHTML=`<div><strong>${results.length}</strong><small>检查项</small></div><div class="configured"><strong>${count('CONFIGURED')}</strong><small>已配置</small></div><div class="missing"><strong>${count('MISSING')}</strong><small>未配置</small></div><div class="struck"><strong>${count('STRUCK_OUT')}</strong><small>已划线</small></div><div class="difference"><strong>${results.filter(r=>r.changed).length}</strong><small>描述差异</small></div><div class="note">描述差异与配置状态独立统计</div>`;
$('filters').innerHTML=[['ALL','全部'],['EXCEPTIONS','仅异常'],['CONFIGURED','已配置'],['MISSING','未配置'],['STRUCK_OUT','已划线']].map(([key,label])=>`<button data-filter="${key}" class="${filter===key?'active':''}" aria-pressed="${filter===key}">${label}</button>`).join('');
const visible=visibleResults();if(!visible.some(r=>r.item.id===selected))selected=visible[0]?.item.id??null;$('visibleCount').textContent=`显示 ${visible.length} / ${results.length}`;
$('resultList').innerHTML=visible.length?visible.map(r=>`<button class="result-row ${selected===r.item.id?'selected':''}" data-select="${escapeHTML(r.item.id)}" aria-pressed="${selected===r.item.id}"><span><small>${escapeHTML(r.item.code)} · ${escapeHTML(r.item.category)}</small><span class="name">${escapeHTML(r.item.name)}</span>${r.changed?'<span class="difference">描述有差异 · 2s → 3s</span>':''}</span>${badge(r)}</button>`).join(''):'<div class="empty">没有符合条件的检查项<p><button id="clearFilters">清除筛选与搜索</button></p></div>';renderDetail();}
$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;renderResults();document.querySelector(`[data-filter="${filter}"]`)?.focus();}};$('search').oninput=renderResults;
$('resultList').onclick=e=>{const b=e.target.closest('[data-select]');if(b){selected=b.dataset.select;renderResults();document.querySelector(`[data-select="${selected}"]`)?.focus();}if(e.target.id==='clearFilters'){filter='ALL';$('search').value='';renderResults();$('search').focus();}};
$('resultList').onkeydown=e=>{if(!['ArrowDown','ArrowUp'].includes(e.key))return;e.preventDefault();const rows=visibleResults(),index=rows.findIndex(r=>r.item.id===selected);selected=rows[Math.max(0,Math.min(rows.length-1,index+(e.key==='ArrowDown'?1:-1)))]?.item.id;renderResults();document.querySelector(`[data-select="${selected}"]`)?.focus();};
function renderDetail(){const r=results.find(r=>r.item.id===selected);if(!r){$('detail').innerHTML='<div class="empty">选择检查项查看要求、证据和原文上下文。</div>';return;}const i=r.item;let actual=escapeHTML(r.actual);if(r.changed)actual=actual.replace('3s','<ins>3s</ins>');if(r.status==='STRUCK_OUT')actual=`<s>${actual}</s>`;let expected=escapeHTML(i.expectedDescription)||'未设置预期描述';if(r.changed)expected=expected.replace('2s','<del>2s</del>');const explanations={EXACT:r.changed?'字面命中功能词“2门控制”；完整描述不一致。EXACT 不代表描述完全相同。':'示例要求文本字面命中；已保留原始文本和来源。',NORMALIZED:'示例仅忽略空白与标点形式差异，保留数值 30 和单位“分钟”。',ALIAS:'命中已配置别名“侧标灯”，对应规范名称“侧标志灯功能”。'};
$('detail').innerHTML=`<div class="detail-title"><div><h2>${escapeHTML(i.name)}</h2><p>${escapeHTML(i.code)} / ${escapeHTML(i.category)}</p></div>${badge(r)}</div><div class="metadata"><span>匹配方式 <b>${r.type||'—'}</b></span><span>证据 <b>${r.actual?'1 处（模拟）':'0 处'}</b></span><span>描述比较 <b>${!i.expectedDescription?'未比较':r.changed?'有差异':r.type==='ALIAS'?'别名命中 · 未比较':r.type==='NORMALIZED'?'规范化后示例一致':r.actual?'示例一致':'无匹配'}</b></span></div><div class="comparison"><div><h3>预期要求 · 检查基准</h3><p>${expected}</p></div><div><h3>实际内容 · 模拟文档</h3><p>${r.actual?actual:'未找到对应内容。请人工确认文档是否使用了其他表述。'}</p></div></div>${r.changed?'<div class="diff-banner"><strong>延时发生变化：2s → 3s</strong><br>功能已出现，但时序描述不同，请核实订单要求。</div>':''}${r.status==='STRUCK_OUT'?'<div class="diff-banner">此处要求全文带删除线，不能作为有效配置直接确认。</div>':''}<section class="evidence"><h3>匹配证据</h3><p>${r.actual?explanations[r.type]:r.noFixture?'此检查项没有预设证据，仅演示未配置状态。未对任何文档执行匹配。':'示例中未发现此功能。未配置是检测结果，不代表已确认无需配置。'}</p><p class="muted">${r.actual?'未提供置信度；匹配方式不等于工程结论。':'没有匹配证据，因此不显示虚构的原文位置。'}</p></section>${r.actual?`<div class="context-title"><h3>原文上下文</h3><span>表 ${r.table} / 行 ${r.row} / 单元格 ${r.cell} / 段 1</span></div><div class="context"><div class="muted"><small>相邻行 · 模拟</small>控制功能要求与订单配置保持一致。</div><div class="current"><small>匹配位置 · 重建摘录，非 Word 页面</small>${actual}</div><div class="muted"><small>相邻行 · 模拟</small>其他未说明部分按基础平台逻辑执行。</div></div>`:'<div class="empty">无原文位置可显示</div>'}`;}
function invalidate(){results=[];selected=null;$('results').hidden=true;$('ready').hidden=!fileName;$('docstate').textContent=fileName?'基准已变更 · 请重新核查':'等待导入';notice('检查基准已变更，旧结果已清除。更改仅在本次会话有效。');$('baselineCount').textContent=items.length;}
function renderManagement(){$('checklist').innerHTML=items.map(i=>`<tr class="${i.enabled?'':'disabled-row'}"><td><small>${escapeHTML(i.code)}</small><strong>${escapeHTML(i.name)}</strong></td><td>${escapeHTML(i.category)||'未分类'}</td><td>${escapeHTML(i.expectedDescription)||'未设置 · 仅核查名称'}</td><td>${i.enabled?'启用':'禁用'}</td><td><button data-edit="${escapeHTML(i.id)}">编辑</button><button data-toggle="${escapeHTML(i.id)}">${i.enabled?'禁用':'启用'}</button><button data-delete="${escapeHTML(i.id)}">删除</button></td></tr>`).join('')||'<tr><td colspan="5">暂无检查项，请新增。</td></tr>';}
$('workspaceTab').onclick=()=>setTab(false);$('manageTab').onclick=()=>setTab(true);
function openEditor(id=null){returnFocus=document.activeElement;editing=id;const i=items.find(x=>x.id===id);$('editForm').reset();$('dialogTitle').textContent=i?'编辑检查项':'新增检查项';for(const key of ['code','name','category','expectedDescription','notes'])$('editForm').elements[key].value=i?.[key]??'';$('editForm').elements.aliases.value=i?.aliases.join('\n')??'';$('editForm').elements.enabled.checked=i?.enabled??true;$('formError').textContent='';$('editor').showModal();}
$('add').onclick=()=>openEditor();$('closeEditor').onclick=$('cancelEditor').onclick=()=>$('editor').close();$('editor').addEventListener('close',()=>returnFocus?.isConnected?returnFocus.focus():$('add').focus());
$('checklist').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)openEditor(b.dataset.edit);if(b.dataset.toggle){const i=items.find(i=>i.id===b.dataset.toggle);i.enabled=!i.enabled;invalidate();renderManagement();document.querySelector(`[data-toggle="${i.id}"]`)?.focus();}if(b.dataset.delete){const i=items.find(i=>i.id===b.dataset.delete);pendingDelete=i.id;$('deleteMessage').textContent=`删除“${i.name}”？`;$('deleteDialog').showModal();}};
let pendingDelete=null;
$('cancelDelete').onclick=()=>$('deleteDialog').close();
$('confirmDelete').onclick=()=>{items=items.filter(x=>x.id!==pendingDelete);invalidate();renderManagement();$('deleteDialog').close();$('add').focus();};
$('editForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),code=data.get('code').trim(),name=data.get('name').trim();if(!code||!name){$('formError').textContent='编号和功能名称不能为空。';return;}if(items.some(i=>i.id!==editing&&(i.code.toLowerCase()===code.toLowerCase()||i.name===name))){$('formError').textContent='编号或功能名称已存在，请使用不同的编号和名称。';return;}const old=items.find(i=>i.id===editing);const item={id:editing||`custom-${Date.now()}`,code,name,category:data.get('category').trim(),expectedDescription:data.get('expectedDescription').trim(),aliases:[...new Set(data.get('aliases').split('\n').map(s=>s.trim()).filter(Boolean))],notes:data.get('notes').trim(),enabled:data.get('enabled')==='on'};
// Edited fixture content cannot inherit evidence for a different requirement.
if(old&&['name','expectedDescription'].every(k=>old[k]===item[k])&&JSON.stringify(old.aliases)===JSON.stringify(item.aliases))item.fixture=old.fixture;
if(old)items=items.map(i=>i.id===editing?item:i);else items.push(item);invalidate();renderManagement();$('editor').close();};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='f'&&!$('results').hidden&&!$('workspace').hidden&&!$('editor').open){e.preventDefault();$('search').focus();}});
